<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * T-TECH-01 (Sprint 4) — table du transport Doctrine de Symfony Messenger.
 *
 * Le DSN async utilise `auto_setup=0` : le schéma du transport est versionné ici plutôt que
 * créé implicitement au runtime (jamais de DDL sur un hôte managé — cohérent avec ARC-88).
 * Le schéma reproduit exactement celui attendu par le transport Doctrine (id en IDENTITY,
 * index combiné) pour que `doctrine:schema:validate` reste vert.
 * Table technique d'infrastructure, sans `tenant_id` : l'isolation par tenant est portée par
 * le message (TenantAwareMessage) et posée à la consommation par le TenantContextMiddleware
 * (ARC-47). Pas de RLS sur cette table.
 */
final class Version20260901120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'T-TECH-01 : table messenger_messages (transport Doctrine, async US-060)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
